name: ebml
version: 0.1.1.0
synopsis: A pure EBML parser
description: |
  Pure decoder for the Extensible Binary Meta Language (EBML) format.

  Use this library to parse mkv/webm file or split a webm stream segments.

  Checkout a motivating use-case presented in this blog post: [Broadcasting a WebM stream using MSE](https://tristancacqueray.github.io/blog/broadcasting-webm).

  Read the haskell-ebml demo app for simple usage: [Main.hs](https://github.com/TristanCacqueray/haskell-ebml/blob/main/app/Main.hs).

author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-ebml
language: GHC2021
category: Codec
extra-source-files:
  - CHANGELOG.md
  - data/firefox-mrec-opus.webm
  - data/*.golden

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -Wno-partial-type-signatures
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wno-missing-methods

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost
  - LambdaCase
  - DerivingStrategies
  - DuplicateRecordFields
  - OverloadedRecordDot
  - BlockArguments
  - StrictData
  - MultiWayIf

dependencies:
  - base < 5
  - bytestring
  - text

library:
  source-dirs: src
  exposed-modules: Codec.EBML
  dependencies:
    - binary
    - containers

executables:
  haskell-ebml:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
    dependencies:
      - ebml

tests:
  spec:
    main: Spec.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
    source-dirs: test
    dependencies:
      - ebml
      - tasty
      - tasty-hunit
      - tasty-golden
      - binary
      - split
      - tasty-quickcheck
